import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { useEffect } from "react";
import { ArrowRight, Gift, GraduationCap, Handshake, School, Sparkles, Star, Trophy, Users, Zap } from "lucide-react";
import { Button } from "../components/ui/button";
import { useAuth } from "../lib/auth-context";

export const Route = createFileRoute("/")({ component: Index, head: () => ({ meta: [{ title: "StarPoints — Achieve. Earn. Shine." }, { name: "description", content: "A smarter way to recognise student achievement." }] }) });

const features = [
  [Trophy, "Recognize Achievement", "Celebrate the good work, kindness and progress that happens every day.", "bg-[#fff5ce] text-[#edab00]"],
  [Sparkles, "Reward Positive Performance", "Turn the effort students put in into moments they can be proud of.", "bg-[#eff1ff] text-[#305ee7]"],
  [Zap, "Track Student Progress", "Give every learner a clear view of their achievements and goals.", "bg-[#e9fbf5] text-[#06a87c]"],
  [Gift, "Unlock Real Rewards", "Create rewards students are genuinely excited to work towards.", "bg-[#f5ecff] text-[#8c49d9]"],
  [Handshake, "Connect Schools & Brands", "Build positive partnerships that bring more opportunities to students.", "bg-[#edf7ff] text-[#0874db]"],
  [Users, "Bring Everyone Together", "Keep teachers, families, schools and reward partners in one place.", "bg-[#fff1ed] text-[#ed744f]"],
] as const;

function ProductCard() {
  return <div className="mx-auto w-full max-w-md rounded-[28px] border-4 border-slate-900 bg-white p-3 shadow-2xl shadow-blue-900/20"><div className="rounded-[19px] bg-[#f6fbff] p-4"><div className="flex items-center justify-between"><span className="text-xs font-extrabold text-[#0874db]">★ StarPoints</span><span className="h-2 w-12 rounded bg-slate-200" /></div><p className="mt-6 text-xs font-bold text-slate-500">My Points</p><div className="mt-1 flex items-center gap-2 text-2xl font-black text-[#053b85]"><Star className="h-6 w-6 fill-[#ffca12] text-[#ffca12]" /> 1,250</div><div className="mt-3 h-2 rounded-full bg-blue-100"><div className="h-full w-[80%] rounded-full bg-gradient-to-r from-[#0974e7] to-[#06b58a]" /></div><p className="mt-6 text-xs font-bold text-slate-500">Recent Achievements</p>{[["Mathematics", "+85"], ["English", "+72"], ["Science", "+90"]].map(([x, p], i) => <div className="mt-3 flex items-center justify-between text-xs" key={x}><span className="flex items-center gap-2 font-bold text-slate-700"><span className={`grid h-5 w-5 place-items-center rounded-full ${i === 0 ? "bg-yellow-100" : i === 1 ? "bg-green-100" : "bg-violet-100"}`}>✦</span>{x}</span><b className="text-[#06a87c]">{p}</b></div>)}<div className="mt-7 flex justify-around border-t pt-3 text-[10px] font-bold text-[#0874db]"><span>⌂<br />Home</span><span>♧<br />Rewards</span><span>♙<br />Profile</span></div></div></div>;
}

function Index() {
  const { isAuthenticated, user, loading } = useAuth(); const navigate = useNavigate();
  useEffect(() => { if (!loading && isAuthenticated && user) { const paths: Record<string, string> = { super_admin: "/super-admin/dashboard", school_admin: "/school-admin/dashboard", admin: "/school-admin/dashboard", branch_admin: "/branch-admin/dashboard", teacher: "/teacher/dashboard", parent: "/parent/dashboard", vendor: "/vendor/dashboard", student: "/student/dashboard" }; navigate({ to: (paths[user.role] || "/student/dashboard") as never }); } }, [loading, isAuthenticated, user, navigate]);
  if (loading || isAuthenticated) return <div className="grid min-h-screen place-items-center"><Sparkles className="animate-pulse text-blue-600" /></div>;
  return <main className="overflow-hidden bg-white text-[#073d7a]">
    <header className="mx-auto flex max-w-7xl items-center justify-between px-5 py-3 sm:px-8"><Link to="/" className="flex items-center gap-2"><img src="/logos/starpoints.png" className="h-11 w-11 object-contain" alt="StarPoints" /><span className="hidden text-xl font-black tracking-tight sm:block">StarPoints<small className="block text-[9px] font-bold">Achieve. Earn. Shine.</small></span></Link><nav className="hidden gap-6 text-xs font-bold lg:flex"><a href="#home" className="text-blue-600">Home</a><a href="#why">About</a><a href="#students">For Students</a><a href="#teachers">For Teachers</a><a href="#schools">For Schools</a><a href="#partners">Reward Partners</a></nav><div className="flex gap-2"><Link to="/login"><Button variant="outline" className="rounded-full border-blue-500 bg-white text-xs font-bold text-blue-700 hover:bg-blue-50">Login</Button></Link><Link to={"/register-school" as any}><Button className="rounded-full bg-[#0874db] text-xs font-bold shadow-md shadow-blue-200 hover:bg-[#065fc0]">Get Started</Button></Link></div></header>
    <section id="home" className="relative isolate bg-gradient-to-r from-[#f8fcff] via-[#e8f7ff] to-[#dbf2ff] px-5 py-14 sm:px-8 lg:py-20"><div className="absolute inset-y-0 right-0 -z-10 hidden w-[44%] bg-gradient-to-br from-blue-200 via-sky-100 to-yellow-100 lg:block" /><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[.95fr_1.05fr]"><div><h1 className="text-4xl font-black tracking-tight sm:text-6xl">Achieve. <span className="text-[#0874db]">Earn.</span> <span className="text-[#f5b900]">Shine.</span><Sparkles className="ml-1 inline h-8 w-8 text-[#f5b900]" /></h1><p className="mt-5 max-w-lg text-lg leading-7 text-[#164b82]">A smarter way to recognize student achievement and turn it into meaningful rewards.</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/student-signup"><Button className="h-11 rounded-xl bg-[#0874db] px-5 font-bold hover:bg-[#065fc0]"><GraduationCap /> I’m a Student</Button></Link><Link to={"/register-school" as any}><Button variant="outline" className="h-11 rounded-xl border-blue-500 bg-white px-5 font-bold text-blue-700 hover:bg-blue-50"><School /> For Schools</Button></Link><a href="#partners"><Button className="h-11 rounded-xl bg-[#06a87c] px-5 font-bold hover:bg-[#058964]"><Handshake /> Become a Reward Partner</Button></a></div></div><div className="relative mx-auto flex w-full max-w-xl justify-center py-4"><div className="absolute h-80 w-80 rounded-full bg-yellow-200/70 blur-2xl" /><div className="relative w-64 rotate-3 sm:w-72"><ProductCard /></div><div className="absolute bottom-2 left-4 rounded-2xl bg-white px-4 py-3 shadow-lg"><p className="text-xs font-bold">Small steps.</p><p className="text-lg font-black text-[#06a87c]">Big dreams.</p></div></div></div></section>
    <section className="bg-[#f7fcff] px-5 py-14 sm:px-8"><div className="mx-auto max-w-6xl text-center"><h2 className="text-2xl font-black sm:text-3xl">How StarPoints Works</h2><p className="mt-2 text-sm">It’s simple. Achievements turn into points, and points turn into rewards.</p><div className="mt-10 grid gap-7 sm:grid-cols-2 lg:grid-cols-4">{[[GraduationCap,"1. Achieve","Students earn StarPoints for academic achievements and positive performance.","bg-[#0874db]"],[Users,"2. Earn Points","Teachers recognize achievements and award points through StarPoints.","bg-[#06a87c]"],[Trophy,"3. Track Progress","Students view their points, achievements and progress in the app or portal.","bg-[#f5b900]"],[Gift,"4. Redeem Rewards","Students use their points to unlock exciting rewards from partners.","bg-[#8c49d9]"]].map(([Icon,title,text,color]) => <div key={title as string}><div className={`mx-auto grid h-16 w-16 place-items-center rounded-full text-white shadow-lg ${color as string}`}><Icon className="h-7 w-7" /></div><h3 className="mt-5 font-black">{title as string}</h3><p className="mx-auto mt-2 max-w-[200px] text-sm leading-5">{text as string}</p></div>)}</div></div></section>
    <section id="why" className="mx-auto grid max-w-7xl gap-10 px-5 py-16 sm:px-8 lg:grid-cols-2 lg:py-24"><div><h2 className="text-3xl font-black">Why StarPoints?</h2><p className="mt-3 text-lg leading-7">We believe every student has a unique ability.<br />Let’s recognize it.</p><div className="mt-8 grid grid-cols-2 gap-3 sm:grid-cols-3">{features.map(([Icon,title,text,tone]) => <div key={title} className="rounded-2xl bg-[#f6faff] p-4 text-center"><div className={`mx-auto grid h-10 w-10 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5" /></div><h3 className="mt-3 text-xs font-black leading-4">{title}</h3><p className="sr-only">{text}</p></div>)}</div></div><div className="relative flex items-center justify-center rounded-[32px] bg-gradient-to-br from-[#effaff] to-[#f9f5ff] p-8"><div className="w-72"><ProductCard /></div><div className="absolute -right-1 top-8 rounded-3xl bg-[#fff4c1] px-4 py-3 text-center text-sm font-black text-[#b57d00] -rotate-6">Your<br />Progress<br />Matters!</div></div></section>
    <section id="students" className="mx-auto grid max-w-7xl gap-5 px-5 pb-20 sm:grid-cols-2 sm:px-8 lg:grid-cols-4">{[["For Students","Your Effort. Your Points. Your Rewards.","Study hard. Participate. Improve. Get recognized. Earn StarPoints. Redeem rewards.","bg-[#fff8dc]","Create Student Account","/student-signup"],["For Teachers","Make Every Achievement Count.","Recognize achievements, award points, track performance and encourage positive behavior.","bg-[#eafbf5]","Teacher Login","/login"],["For Schools","Build a Culture of Achievement.","Digital reward management, student engagement, tracking and reporting — all in one place.","bg-[#eaf5ff]","Register Your School","/register-school"],["Reward Partners","Turn Your Brand Into a Student Reward.","Reach students through meaningful rewards — not just advertising.","bg-[#f7efff]","Become a Reward Partner","#partners"]].map(([eyebrow,title,text,bg,cta,path], i) => <article id={i === 1 ? "teachers" : i === 2 ? "schools" : i === 3 ? "partners" : undefined} key={eyebrow} className={`rounded-2xl border border-slate-100 p-5 ${bg}`}><div className="mb-6 h-20 rounded-xl bg-white/70" /><p className="text-sm font-black">{eyebrow}</p><h3 className="mt-3 min-h-14 text-lg font-black leading-5">{title}</h3><p className="mt-3 min-h-20 text-sm leading-5">{text}</p>{path.startsWith("/") ? <Link to={path as any}><Button className="mt-5 rounded-lg bg-[#0874db] text-xs font-bold hover:bg-[#065fc0]">{cta} <ArrowRight /></Button></Link> : <a href={path}><Button className="mt-5 rounded-lg bg-[#8c49d9] text-xs font-bold hover:bg-[#7032bc]">{cta} <ArrowRight /></Button></a>}</article>)}</section>
    <section className="border-t border-blue-50 bg-white px-5 py-16 sm:px-8"><div className="mx-auto grid max-w-6xl items-center gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><h2 className="text-3xl font-black">The StarPoints Ecosystem</h2><p className="mt-4 max-w-sm leading-6">Bringing together schools, teachers, students and partners—for a brighter future for every child.</p></div><div className="relative mx-auto grid w-full max-w-xl grid-cols-3 items-center gap-4 text-center"><div className="rounded-full border border-blue-100 bg-[#eef7ff] p-5"><School className="mx-auto h-7 w-7 text-[#0874db]" /><p className="mt-2 text-xs font-black">Schools</p></div><div className="row-span-2 grid aspect-square place-items-center rounded-full border-4 border-[#0874db] bg-white p-5 shadow-xl shadow-blue-100"><div><Star className="mx-auto h-10 w-10 fill-[#ffcb1c] text-[#ffcb1c]" /><p className="mt-2 text-lg font-black">StarPoints</p></div></div><div className="rounded-full border border-emerald-100 bg-[#e8fbf5] p-5"><Users className="mx-auto h-7 w-7 text-[#06a87c]" /><p className="mt-2 text-xs font-black">Teachers</p></div><div className="rounded-full border border-violet-100 bg-[#f5edff] p-5"><Handshake className="mx-auto h-7 w-7 text-[#8c49d9]" /><p className="mt-2 text-xs font-black">Partners</p></div><div className="rounded-full border border-yellow-100 bg-[#fff9df] p-5"><GraduationCap className="mx-auto h-7 w-7 text-[#e0a400]" /><p className="mt-2 text-xs font-black">Students</p></div></div></div></section>
    <section className="border-y border-blue-50 bg-white px-5 py-7 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 sm:flex-row"><div><p className="font-black">Our Reward Partners</p><p className="text-sm">Trusted brands. Real rewards.</p></div><div className="flex flex-wrap items-center justify-center gap-x-8 gap-y-3 text-lg font-black text-slate-400"><span>nestlé</span><span className="text-red-500">EBM</span><span className="text-amber-600">Books & Beyond</span><span className="text-emerald-500">careem</span><span className="text-red-500">TCS</span></div></div></section>
    <section className="bg-gradient-to-r from-[#f6fffd] to-[#f2faff] px-5 py-11 sm:px-8"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-6 text-center lg:flex-row lg:text-left"><div><h2 className="text-2xl font-black">Our Impact</h2><p>Real change. Brighter futures.</p></div><div className="grid grid-cols-2 gap-6 text-center sm:grid-cols-4">{[["500+","Schools"],["25,000+","Students"],["100,000+","Achievements"],["50+","Reward Partners"]].map(([number,label]) => <div key={label}><p className="text-2xl font-black text-[#0874db]">{number}</p><p className="text-xs font-bold">{label}</p></div>)}</div></div></section>
    <section className="bg-[#0874db] px-5 py-14 text-center text-white sm:px-8"><h2 className="text-3xl font-black">Every Child Has the Ability to Shine.</h2><p className="mx-auto mt-3 max-w-lg">Let’s recognize their effort, celebrate their achievements, and give them something to look forward to.</p><Link to={"/register-school" as any}><Button className="mt-7 h-11 rounded-full bg-[#ffcb1c] px-7 font-bold text-[#073d7a] hover:bg-[#ffd84f]">Join StarPoints Today <ArrowRight /></Button></Link></section>
    <footer className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 px-5 py-8 text-xs sm:flex-row sm:px-8"><Link to="/" className="flex items-center gap-2 font-black"><img src="/logos/starpoints.png" className="h-8 w-8" alt="" />StarPoints</Link><div className="flex gap-4 font-bold"><a href="#home">Home</a><a href="#why">About</a><a href="#students">For Students</a><a href="#schools">For Schools</a></div><span>© {new Date().getFullYear()} StarPoints</span></footer>
  </main>;
}
