/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTeacherRouteImport } from './routes/_authenticated.teacher'
import { Route as AuthenticatedStudentRouteImport } from './routes/_authenticated.student'
import { Route as AuthenticatedParentRouteImport } from './routes/_authenticated.parent'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedTeacherScanRouteImport } from './routes/_authenticated.teacher.scan'
import { Route as AuthenticatedTeacherRewardsRouteImport } from './routes/_authenticated.teacher.rewards'
import { Route as AuthenticatedTeacherHistoryRouteImport } from './routes/_authenticated.teacher.history'
import { Route as AuthenticatedTeacherDashboardRouteImport } from './routes/_authenticated.teacher.dashboard'
import { Route as AuthenticatedStudentRewardsRouteImport } from './routes/_authenticated.student.rewards'
import { Route as AuthenticatedStudentQrRouteImport } from './routes/_authenticated.student.qr'
import { Route as AuthenticatedStudentHistoryRouteImport } from './routes/_authenticated.student.history'
import { Route as AuthenticatedStudentDashboardRouteImport } from './routes/_authenticated.student.dashboard'
import { Route as AuthenticatedParentProfileRouteImport } from './routes/_authenticated.parent.profile'
import { Route as AuthenticatedParentNotificationsRouteImport } from './routes/_authenticated.parent.notifications'
import { Route as AuthenticatedParentMessagesRouteImport } from './routes/_authenticated.parent.messages'
import { Route as AuthenticatedParentDashboardRouteImport } from './routes/_authenticated.parent.dashboard'
import { Route as AuthenticatedAdminTeachersRouteImport } from './routes/_authenticated.admin.teachers'
import { Route as AuthenticatedAdminStudentsRouteImport } from './routes/_authenticated.admin.students'
import { Route as AuthenticatedAdminRulesRouteImport } from './routes/_authenticated.admin.rules'
import { Route as AuthenticatedAdminRewardsRouteImport } from './routes/_authenticated.admin.rewards'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated.admin.profile'
import { Route as AuthenticatedAdminParentsRouteImport } from './routes/_authenticated.admin.parents'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated.admin.dashboard'
import { Route as AuthenticatedAdminClassesRouteImport } from './routes/_authenticated.admin.classes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTeacherRoute = AuthenticatedTeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStudentRoute = AuthenticatedStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedParentRoute = AuthenticatedParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeacherScanRoute =
  AuthenticatedTeacherScanRouteImport.update({
    id: '/scan',
    path: '/scan',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherRewardsRoute =
  AuthenticatedTeacherRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherHistoryRoute =
  AuthenticatedTeacherHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedTeacherDashboardRoute =
  AuthenticatedTeacherDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedTeacherRoute,
  } as any)
const AuthenticatedStudentRewardsRoute =
  AuthenticatedStudentRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentQrRoute = AuthenticatedStudentQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedStudentRoute,
} as any)
const AuthenticatedStudentHistoryRoute =
  AuthenticatedStudentHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedStudentDashboardRoute =
  AuthenticatedStudentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedStudentRoute,
  } as any)
const AuthenticatedParentProfileRoute =
  AuthenticatedParentProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentNotificationsRoute =
  AuthenticatedParentNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentMessagesRoute =
  AuthenticatedParentMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedParentDashboardRoute =
  AuthenticatedParentDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedParentRoute,
  } as any)
const AuthenticatedAdminTeachersRoute =
  AuthenticatedAdminTeachersRouteImport.update({
    id: '/teachers',
    path: '/teachers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminStudentsRoute =
  AuthenticatedAdminStudentsRouteImport.update({
    id: '/students',
    path: '/students',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminRulesRoute = AuthenticatedAdminRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminRewardsRoute =
  AuthenticatedAdminRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminParentsRoute =
  AuthenticatedAdminParentsRouteImport.update({
    id: '/parents',
    path: '/parents',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminClassesRoute =
  AuthenticatedAdminClassesRouteImport.update({
    id: '/classes',
    path: '/classes',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/parent': typeof AuthenticatedParentRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/parents': typeof AuthenticatedAdminParentsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/parent/dashboard': typeof AuthenticatedParentDashboardRoute
  '/parent/messages': typeof AuthenticatedParentMessagesRoute
  '/parent/notifications': typeof AuthenticatedParentNotificationsRoute
  '/parent/profile': typeof AuthenticatedParentProfileRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/qr': typeof AuthenticatedStudentQrRoute
  '/student/rewards': typeof AuthenticatedStudentRewardsRoute
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/history': typeof AuthenticatedTeacherHistoryRoute
  '/teacher/rewards': typeof AuthenticatedTeacherRewardsRoute
  '/teacher/scan': typeof AuthenticatedTeacherScanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/parent': typeof AuthenticatedParentRouteWithChildren
  '/student': typeof AuthenticatedStudentRouteWithChildren
  '/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/parents': typeof AuthenticatedAdminParentsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/parent/dashboard': typeof AuthenticatedParentDashboardRoute
  '/parent/messages': typeof AuthenticatedParentMessagesRoute
  '/parent/notifications': typeof AuthenticatedParentNotificationsRoute
  '/parent/profile': typeof AuthenticatedParentProfileRoute
  '/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/student/history': typeof AuthenticatedStudentHistoryRoute
  '/student/qr': typeof AuthenticatedStudentQrRoute
  '/student/rewards': typeof AuthenticatedStudentRewardsRoute
  '/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/teacher/history': typeof AuthenticatedTeacherHistoryRoute
  '/teacher/rewards': typeof AuthenticatedTeacherRewardsRoute
  '/teacher/scan': typeof AuthenticatedTeacherScanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/parent': typeof AuthenticatedParentRouteWithChildren
  '/_authenticated/student': typeof AuthenticatedStudentRouteWithChildren
  '/_authenticated/teacher': typeof AuthenticatedTeacherRouteWithChildren
  '/_authenticated/admin/classes': typeof AuthenticatedAdminClassesRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/parents': typeof AuthenticatedAdminParentsRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/_authenticated/admin/rules': typeof AuthenticatedAdminRulesRoute
  '/_authenticated/admin/students': typeof AuthenticatedAdminStudentsRoute
  '/_authenticated/admin/teachers': typeof AuthenticatedAdminTeachersRoute
  '/_authenticated/parent/dashboard': typeof AuthenticatedParentDashboardRoute
  '/_authenticated/parent/messages': typeof AuthenticatedParentMessagesRoute
  '/_authenticated/parent/notifications': typeof AuthenticatedParentNotificationsRoute
  '/_authenticated/parent/profile': typeof AuthenticatedParentProfileRoute
  '/_authenticated/student/dashboard': typeof AuthenticatedStudentDashboardRoute
  '/_authenticated/student/history': typeof AuthenticatedStudentHistoryRoute
  '/_authenticated/student/qr': typeof AuthenticatedStudentQrRoute
  '/_authenticated/student/rewards': typeof AuthenticatedStudentRewardsRoute
  '/_authenticated/teacher/dashboard': typeof AuthenticatedTeacherDashboardRoute
  '/_authenticated/teacher/history': typeof AuthenticatedTeacherHistoryRoute
  '/_authenticated/teacher/rewards': typeof AuthenticatedTeacherRewardsRoute
  '/_authenticated/teacher/scan': typeof AuthenticatedTeacherScanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/parents'
    | '/admin/profile'
    | '/admin/rewards'
    | '/admin/rules'
    | '/admin/students'
    | '/admin/teachers'
    | '/parent/dashboard'
    | '/parent/messages'
    | '/parent/notifications'
    | '/parent/profile'
    | '/student/dashboard'
    | '/student/history'
    | '/student/qr'
    | '/student/rewards'
    | '/teacher/dashboard'
    | '/teacher/history'
    | '/teacher/rewards'
    | '/teacher/scan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/parent'
    | '/student'
    | '/teacher'
    | '/admin/classes'
    | '/admin/dashboard'
    | '/admin/parents'
    | '/admin/profile'
    | '/admin/rewards'
    | '/admin/rules'
    | '/admin/students'
    | '/admin/teachers'
    | '/parent/dashboard'
    | '/parent/messages'
    | '/parent/notifications'
    | '/parent/profile'
    | '/student/dashboard'
    | '/student/history'
    | '/student/qr'
    | '/student/rewards'
    | '/teacher/dashboard'
    | '/teacher/history'
    | '/teacher/rewards'
    | '/teacher/scan'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/admin'
    | '/_authenticated/parent'
    | '/_authenticated/student'
    | '/_authenticated/teacher'
    | '/_authenticated/admin/classes'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/parents'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/rewards'
    | '/_authenticated/admin/rules'
    | '/_authenticated/admin/students'
    | '/_authenticated/admin/teachers'
    | '/_authenticated/parent/dashboard'
    | '/_authenticated/parent/messages'
    | '/_authenticated/parent/notifications'
    | '/_authenticated/parent/profile'
    | '/_authenticated/student/dashboard'
    | '/_authenticated/student/history'
    | '/_authenticated/student/qr'
    | '/_authenticated/student/rewards'
    | '/_authenticated/teacher/dashboard'
    | '/_authenticated/teacher/history'
    | '/_authenticated/teacher/rewards'
    | '/_authenticated/teacher/scan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teacher': {
      id: '/_authenticated/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof AuthenticatedTeacherRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/student': {
      id: '/_authenticated/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof AuthenticatedStudentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/parent': {
      id: '/_authenticated/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof AuthenticatedParentRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teacher/scan': {
      id: '/_authenticated/teacher/scan'
      path: '/scan'
      fullPath: '/teacher/scan'
      preLoaderRoute: typeof AuthenticatedTeacherScanRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/rewards': {
      id: '/_authenticated/teacher/rewards'
      path: '/rewards'
      fullPath: '/teacher/rewards'
      preLoaderRoute: typeof AuthenticatedTeacherRewardsRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/history': {
      id: '/_authenticated/teacher/history'
      path: '/history'
      fullPath: '/teacher/history'
      preLoaderRoute: typeof AuthenticatedTeacherHistoryRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/teacher/dashboard': {
      id: '/_authenticated/teacher/dashboard'
      path: '/dashboard'
      fullPath: '/teacher/dashboard'
      preLoaderRoute: typeof AuthenticatedTeacherDashboardRouteImport
      parentRoute: typeof AuthenticatedTeacherRoute
    }
    '/_authenticated/student/rewards': {
      id: '/_authenticated/student/rewards'
      path: '/rewards'
      fullPath: '/student/rewards'
      preLoaderRoute: typeof AuthenticatedStudentRewardsRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/qr': {
      id: '/_authenticated/student/qr'
      path: '/qr'
      fullPath: '/student/qr'
      preLoaderRoute: typeof AuthenticatedStudentQrRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/history': {
      id: '/_authenticated/student/history'
      path: '/history'
      fullPath: '/student/history'
      preLoaderRoute: typeof AuthenticatedStudentHistoryRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/student/dashboard': {
      id: '/_authenticated/student/dashboard'
      path: '/dashboard'
      fullPath: '/student/dashboard'
      preLoaderRoute: typeof AuthenticatedStudentDashboardRouteImport
      parentRoute: typeof AuthenticatedStudentRoute
    }
    '/_authenticated/parent/profile': {
      id: '/_authenticated/parent/profile'
      path: '/profile'
      fullPath: '/parent/profile'
      preLoaderRoute: typeof AuthenticatedParentProfileRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/notifications': {
      id: '/_authenticated/parent/notifications'
      path: '/notifications'
      fullPath: '/parent/notifications'
      preLoaderRoute: typeof AuthenticatedParentNotificationsRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/messages': {
      id: '/_authenticated/parent/messages'
      path: '/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof AuthenticatedParentMessagesRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/parent/dashboard': {
      id: '/_authenticated/parent/dashboard'
      path: '/dashboard'
      fullPath: '/parent/dashboard'
      preLoaderRoute: typeof AuthenticatedParentDashboardRouteImport
      parentRoute: typeof AuthenticatedParentRoute
    }
    '/_authenticated/admin/teachers': {
      id: '/_authenticated/admin/teachers'
      path: '/teachers'
      fullPath: '/admin/teachers'
      preLoaderRoute: typeof AuthenticatedAdminTeachersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/students': {
      id: '/_authenticated/admin/students'
      path: '/students'
      fullPath: '/admin/students'
      preLoaderRoute: typeof AuthenticatedAdminStudentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rules': {
      id: '/_authenticated/admin/rules'
      path: '/rules'
      fullPath: '/admin/rules'
      preLoaderRoute: typeof AuthenticatedAdminRulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/rewards': {
      id: '/_authenticated/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AuthenticatedAdminRewardsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/parents': {
      id: '/_authenticated/admin/parents'
      path: '/parents'
      fullPath: '/admin/parents'
      preLoaderRoute: typeof AuthenticatedAdminParentsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/classes': {
      id: '/_authenticated/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AuthenticatedAdminClassesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminClassesRoute: typeof AuthenticatedAdminClassesRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminParentsRoute: typeof AuthenticatedAdminParentsRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminRewardsRoute: typeof AuthenticatedAdminRewardsRoute
  AuthenticatedAdminRulesRoute: typeof AuthenticatedAdminRulesRoute
  AuthenticatedAdminStudentsRoute: typeof AuthenticatedAdminStudentsRoute
  AuthenticatedAdminTeachersRoute: typeof AuthenticatedAdminTeachersRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminClassesRoute: AuthenticatedAdminClassesRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminParentsRoute: AuthenticatedAdminParentsRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminRewardsRoute: AuthenticatedAdminRewardsRoute,
  AuthenticatedAdminRulesRoute: AuthenticatedAdminRulesRoute,
  AuthenticatedAdminStudentsRoute: AuthenticatedAdminStudentsRoute,
  AuthenticatedAdminTeachersRoute: AuthenticatedAdminTeachersRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedParentRouteChildren {
  AuthenticatedParentDashboardRoute: typeof AuthenticatedParentDashboardRoute
  AuthenticatedParentMessagesRoute: typeof AuthenticatedParentMessagesRoute
  AuthenticatedParentNotificationsRoute: typeof AuthenticatedParentNotificationsRoute
  AuthenticatedParentProfileRoute: typeof AuthenticatedParentProfileRoute
}

const AuthenticatedParentRouteChildren: AuthenticatedParentRouteChildren = {
  AuthenticatedParentDashboardRoute: AuthenticatedParentDashboardRoute,
  AuthenticatedParentMessagesRoute: AuthenticatedParentMessagesRoute,
  AuthenticatedParentNotificationsRoute: AuthenticatedParentNotificationsRoute,
  AuthenticatedParentProfileRoute: AuthenticatedParentProfileRoute,
}

const AuthenticatedParentRouteWithChildren =
  AuthenticatedParentRoute._addFileChildren(AuthenticatedParentRouteChildren)

interface AuthenticatedStudentRouteChildren {
  AuthenticatedStudentDashboardRoute: typeof AuthenticatedStudentDashboardRoute
  AuthenticatedStudentHistoryRoute: typeof AuthenticatedStudentHistoryRoute
  AuthenticatedStudentQrRoute: typeof AuthenticatedStudentQrRoute
  AuthenticatedStudentRewardsRoute: typeof AuthenticatedStudentRewardsRoute
}

const AuthenticatedStudentRouteChildren: AuthenticatedStudentRouteChildren = {
  AuthenticatedStudentDashboardRoute: AuthenticatedStudentDashboardRoute,
  AuthenticatedStudentHistoryRoute: AuthenticatedStudentHistoryRoute,
  AuthenticatedStudentQrRoute: AuthenticatedStudentQrRoute,
  AuthenticatedStudentRewardsRoute: AuthenticatedStudentRewardsRoute,
}

const AuthenticatedStudentRouteWithChildren =
  AuthenticatedStudentRoute._addFileChildren(AuthenticatedStudentRouteChildren)

interface AuthenticatedTeacherRouteChildren {
  AuthenticatedTeacherDashboardRoute: typeof AuthenticatedTeacherDashboardRoute
  AuthenticatedTeacherHistoryRoute: typeof AuthenticatedTeacherHistoryRoute
  AuthenticatedTeacherRewardsRoute: typeof AuthenticatedTeacherRewardsRoute
  AuthenticatedTeacherScanRoute: typeof AuthenticatedTeacherScanRoute
}

const AuthenticatedTeacherRouteChildren: AuthenticatedTeacherRouteChildren = {
  AuthenticatedTeacherDashboardRoute: AuthenticatedTeacherDashboardRoute,
  AuthenticatedTeacherHistoryRoute: AuthenticatedTeacherHistoryRoute,
  AuthenticatedTeacherRewardsRoute: AuthenticatedTeacherRewardsRoute,
  AuthenticatedTeacherScanRoute: AuthenticatedTeacherScanRoute,
}

const AuthenticatedTeacherRouteWithChildren =
  AuthenticatedTeacherRoute._addFileChildren(AuthenticatedTeacherRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedParentRoute: typeof AuthenticatedParentRouteWithChildren
  AuthenticatedStudentRoute: typeof AuthenticatedStudentRouteWithChildren
  AuthenticatedTeacherRoute: typeof AuthenticatedTeacherRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedParentRoute: AuthenticatedParentRouteWithChildren,
  AuthenticatedStudentRoute: AuthenticatedStudentRouteWithChildren,
  AuthenticatedTeacherRoute: AuthenticatedTeacherRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
